create database DATABASE_TPCH;
create schema SCHEMA_TPCH;

CREATE OR REPLACE TABLE REGION (
  R_REGIONKEY INT PRIMARY KEY,
  R_NAME VARCHAR(25),
  R_COMMENT VARCHAR(152)
);

CREATE OR REPLACE TABLE NATION (
  N_NATIONKEY INT PRIMARY KEY,
  N_NAME CHAR(25),
  N_REGIONKEY INT,
  N_COMMENT VARCHAR(152),
  FOREIGN KEY (N_REGIONKEY) REFERENCES region (R_REGIONKEY)
);

CREATE OR REPLACE TABLE CUSTOMER (
  C_CUSTKEY      INT PRIMARY KEY,
  C_NAME         VARCHAR(25),
  C_ADDRESS      VARCHAR(40),
  C_NATIONKEY    INT,
  C_PHONE        CHAR(15),
  C_ACCTBAL      DECIMAL(15, 2),
  C_MKTSEGMENT   CHAR(10),
  C_COMMENT      VARCHAR(117),
  FOREIGN KEY (C_NATIONKEY) REFERENCES nation(N_NATIONKEY)
);

CREATE OR REPLACE TABLE ORDERS (
  O_ORDERKEY       INT PRIMARY KEY,
  O_CUSTKEY        INT,
  O_ORDERSTATUS    CHAR(1),
  O_TOTALPRICE     DECIMAL(15, 2),
  O_ORDERDATE      DATE,
  O_ORDERPRIORITY  CHAR(15),
  O_CLERK          CHAR(15),
  O_SHIPPRIORITY   INT,
  O_COMMENT        VARCHAR(79),
  FOREIGN KEY (O_CUSTKEY) REFERENCES customer(C_CUSTKEY)
);

CREATE OR REPLACE TABLE PART (
  P_PARTKEY     INT PRIMARY KEY,
  P_NAME        VARCHAR(55) NOT NULL,
  P_MFGR        CHAR(25) NOT NULL,
  P_BRAND       CHAR(10) NOT NULL,
  P_TYPE        VARCHAR(25) NOT NULL,
  P_SIZE        INT NOT NULL,
  P_CONTAINER   CHAR(10) NOT NULL,
  P_RETAILPRICE DECIMAL(15,2) NOT NULL,
  P_COMMENT     VARCHAR(23) NOT NULL
);

CREATE OR REPLACE TABLE SUPPLIER (
  S_SUPPKEY     INT PRIMARY KEY,
  S_NAME        CHAR(25) NOT NULL,
  S_ADDRESS     VARCHAR(40) NOT NULL,
  S_NATIONKEY   INT NOT NULL,
  S_PHONE       CHAR(15) NOT NULL,
  S_ACCTBAL     DECIMAL(15,2) NOT NULL,
  S_COMMENT     VARCHAR(101) NOT NULL,
  FOREIGN KEY (S_NATIONKEY) REFERENCES NATION (N_NATIONKEY)
);

CREATE OR REPLACE TABLE PARTSUPP (
  PS_PARTKEY     INT NOT NULL,
  PS_SUPPKEY     INT NOT NULL,
  PS_AVAILQTY    INT NOT NULL,
  PS_SUPPLYCOST  DECIMAL(15,2) NOT NULL,
  PS_COMMENT     VARCHAR(199) NOT NULL,
  PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
  FOREIGN KEY (PS_PARTKEY) REFERENCES PART (P_PARTKEY),
  FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER (S_SUPPKEY)
);

CREATE OR REPLACE TABLE LINEITEM (
  L_ORDERKEY INT NOT NULL,
  L_PARTKEY INT,
  L_SUPPKEY INT NOT NULL,
  L_LINENUMBER INT NOT NULL,
  L_QUANTITY DECIMAL(15, 2),
  L_EXTENDEDPRICE DECIMAL(15, 2),
  L_DISCOUNT DECIMAL(15, 2),
  L_TAX DECIMAL(15, 2),
  L_RETURNFLAG CHAR(1),
  L_LINESTATUS CHAR(1),
  L_SHIPDATE DATE,
  L_COMMITDATE DATE,
  L_RECEIPTDATE DATE,
  L_SHIPINSTRUCT CHAR(25),
  L_SHIPMODE CHAR(10),
  L_COMMENT VARCHAR(44),
  PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
  FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS (O_ORDERKEY),
  FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES PARTSUPP (PS_PARTKEY, PS_SUPPKEY)
);

CREATE OR REPLACE TABLE SCHEMA_TPCH.PROCESS_LOG (
	PROCESS_ID NUMBER(38,0) autoincrement,
	EXECUTION_STEP VARCHAR(500),
	EXECUTION_STATUS VARCHAR(50),
	PROCESS_NAME VARCHAR(50),
	EXECUTION_END_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	ERROR_CODE VARCHAR(50),
	ERROR_STATE VARCHAR(500),
	ERROR_MESSAGE VARCHAR(500),
	ERROR_STACK_TEXT VARCHAR(500)
);

INSERT INTO REGION
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;

INSERT INTO NATION
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

INSERT INTO CUSTOMER
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

INSERT INTO ORDERS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

INSERT INTO PART
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

INSERT INTO SUPPLIER
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;

INSERT INTO PARTSUPP
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;

INSERT INTO LINEITEM
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;
